export enum KnownMimeTypes {
	csv = 'text/csv',
	doc = 'application/msword',
	docx = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	gif = 'image/gif',
	jpeg = 'image/jpeg',
	jpg = 'image/jpeg',
	json = 'application/json',
	pdf = 'application/pdf',
	png = 'image/png',
	ppt = 'application/vnd.ms-powerpoint',
	pptx = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	txt = 'text/plain',
	xls = 'application/vnd.ms-excel',
	xlsm = 'application/vnd.ms-excel.sheet.macroEnabled.12',
	xlsx = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	xml = 'application/xml',
}
