/**
 * THIS FILE IS AUTOGENERATED ON EACH BUILD
 * DO NOT CHANGE THE CONTENTS OF THIS FILE
 * CHANGES MADE IN THIS FILE WILL BE OVERWRITTEN DURING THE NEXT BUILD
 */

/**
 * ERRORHANDLING
 */
export {
	ICustomValidationError,
	ICustomErrorDetail,
	ICustomError,
	IBodyError,
	IHeadersError,
	IParamsError,
	IQueryError,
	IMigrationsRunningError,
	IUnauthorizedError,
	IForbiddenError,
	INotFoundError,
	IConflictError,
	IInternalServerError,
	IErrors,
} from './types/errorhandling';

/**
 * REQUEST
 */
export {
	IRequest,
	IResponse,
	INext,
	IPagination,
	IPaginationQuery,
	IQuery,
} from './types/request';

/**
 * SEQUELIZE
 */
export {
	ModelStatic,
} from './types/sequelize';

/**
 * VALIDATION
 */
export {
	IValidationPreset,
	IValidationOrigin,
	IValidationError,
} from './types/validation';
