/**
 * THIS FILE IS AUTOGENERATED ON EACH BUILD
 * DO NOT CHANGE THE CONTENTS OF THIS FILE
 * CHANGES MADE IN THIS FILE WILL BE OVERWRITTEN DURING THE NEXT BUILD
 */

/**
 * AUTH_CONF
 */
export {
	AUTH_CONFIG,
} from './lib/auth.conf';

/**
 * AUTH_GUARD
 */
export {
	AuthGuard,
} from './lib/auth.guard';

/**
 * AUTH_INTERCEPTOR
 */
export {
	AuthInterceptor,
} from './lib/auth.interceptor';

/**
 * AUTH_MODULE
 */
export {
	AuthModule,
} from './lib/auth.module';

/**
 * AUTH_SERVICE
 */
export {
	AuthService,
} from './lib/auth.service';

/**
 * AUTH_TYPES
 */
export {
	IAuthConfig,
	IAuthConfigFactory,
	IAuth0Client,
	ICreateAuth0Client,
} from './lib/auth.types';

/**
 * CALLBACK_COMPONENT
 */
export {
	CallbackComponent,
} from './lib/callback.component';

/**
 * LOGIN_COMPONENT
 */
export {
	LoginComponent,
} from './lib/login.component';

